# Generated by Django 3.2.4 on 2021-07-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
