# Generated by Django 3.2.4 on 2021-07-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museos_app', '0003_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='users',
            field=models.ManyToManyField(related_name='museums', to='museos_app.User'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='museos_app.user'),
        ),
    ]
