# Generated by Django 3.2.4 on 2021-07-19 00:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('museos_app', '0004_auto_20210718_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='museos_app.museum'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='museos_app.museum'),
        ),
    ]
