# Generated by Django 3.2.4 on 2021-07-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museos_app', '0006_auto_20210719_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohpinions', to='museos_app.museum'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateeng', to='museos_app.museum'),
        ),
    ]
