# Generated by Django 3.2.4 on 2021-07-19 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museos_app', '0007_auto_20210719_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='museum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='museos_app.museum'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='museum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='museos_app.museum'),
        ),
    ]
